import "@/app/globals.css";
import SwitchThemeBtn from "@/components/SwitchThemeBtn";
import { DarkModeProvider } from "@/context/DarkModeContext";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="fr">
            <body className="p-20">
                <DarkModeProvider>
                    <SwitchThemeBtn />
                    {children}
                </DarkModeProvider>
            </body>
        </html>
    );
}
